#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

# Repo-relative paths, so the wizard works from any cwd.
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="$REPO_ROOT/.play-launch.env"          # gitignored: the repo is PUBLIC
AAB="$REPO_ROOT/app/build/outputs/bundle/playRelease/app-play-release.aab"
GRADLE_VERSION_FILE="$REPO_ROOT/app/build.gradle.kts"
JBR="/c/Program Files/Android/Android Studio/jbr"
CONSOLE="https://play.google.com/console"

banner "Corlang: Play Console launch"

# -- 1 ---------------------------------------------------------------------
stage "Preflight: the artefact"
say "Play needs a fresh AAB. build/ is gitignored, so it may not exist at all."

DECLARED_VC=$(grep -E '^\s*versionCode\s*=' "$GRADLE_VERSION_FILE" | head -n1 | tr -dc '0-9' || true)
DECLARED_VN=$(grep -E '^\s*versionName\s*=' "$GRADLE_VERSION_FILE" | head -n1 | sed 's/.*"\(.*\)".*/\1/' || true)
note "source declares versionCode $DECLARED_VC / versionName $DECLARED_VN"

REBUILD=no
if [[ ! -f "$AAB" ]]; then
  warn "no AAB at app/build/outputs/bundle/playRelease/ - it has to be built."
  REBUILD=yes
elif [[ "$GRADLE_VERSION_FILE" -nt "$AAB" ]]; then
  warn "the AAB is OLDER than app/build.gradle.kts, so its versionCode is stale."
  note "uploading a stale bundle wastes a versionCode: Play never accepts the same one twice."
  REBUILD=yes
else
  note "AAB present and newer than the version file."
  note "$(ls -l "$AAB" | awk '{print $5" bytes, "$6" "$7" "$8}')"
  if command -v sha256sum >/dev/null 2>&1; then note "sha256 $(sha256sum "$AAB" | cut -c1-16)..."; fi
fi

if [[ "$REBUILD" == yes ]]; then
  say "Rebuild command (JAVA_HOME must be the Android Studio JBR, JDK 21):"
  note "  JAVA_HOME=\"$JBR\" ./gradlew :app:bundlePlayRelease"
  if confirm "Run that now? (takes a few minutes)"; then
    if ( cd "$REPO_ROOT" && JAVA_HOME="$JBR" ./gradlew :app:bundlePlayRelease --console=plain ); then
      say "built."
    else
      warn "the build FAILED - read the gradle output above before going any further."
      SKIPPED+=("rebuild the play AAB: the build failed")
    fi
  else
    SKIPPED+=("rebuild the play AAB before uploading (stage 7 needs it)")
    warn "carrying on, but do NOT upload the stale file."
  fi
fi

if [[ -f "$AAB" ]] && command -v unzip >/dev/null 2>&1; then
  say "Checking what is actually inside the bundle:"
  SHIPPED=$(unzip -l "$AAB" | grep -oE 'assets/content/[a-z]{2}/' | sort -u | tr '\n' ' ' || true)
  note "courses shipped: ${SHIPPED:-none found}"
  if [[ "$SHIPPED" == *"assets/content/hr/"* && "$SHIPPED" == *"assets/content/pt/"* ]]; then
    say "hr + pt present."
  else
    warn "expected hr and pt only - check content/_index.json and stageLiveAssets."
  fi
  if unzip -l "$AAB" | grep -q 'META-INF/.*\.RSA'; then say "signed."; else warn "no signature block found."; fi
fi
note "the permission checks (BILLING present, REQUEST_INSTALL_PACKAGES absent) hold for the"
note "play flavor by construction: it compiles the in-app updater out. See docs/PENDING.md."
write_env AAB_VERSION_CODE "$DECLARED_VC"
pause "Artefact ready?"

# -- 2 ---------------------------------------------------------------------
stage "Play Console: the app record"
say "The app should already exist - App access was answered and saved on 2026-08-22."
open_url "$CONSOLE"
step "All apps: confirm 'Corlang' is listed."
step "If it is NOT: Create app - name 'Corlang', type App, Free, default language English."
note "package name com.corlang.app is fixed by app/build.gradle.kts and can never change"
note "after the first upload."
ask PLAY_APP_URL "Paste the console URL of the app (the one containing /app/):"
write_env PLAY_APP_URL "$PLAY_APP_URL"

# -- 3 ---------------------------------------------------------------------
stage "Main store listing"
say "Grow the listing from the drafted copy. Do not retype it from memory."
open_url "$CONSOLE"
step "Grow your app > Main store listing."
say ""
say "App name:          Corlang - Learn Croatian & Portuguese"
say "Short description: Learn Croatian or European Portuguese with a real day-by-day plan."
note "full description: docs/road-to-play.md, section 'Store listing copy' - copy it verbatim"
say ""
step "App icon:        docs/store-assets/play-icon-512.png (512x512)"
step "Feature graphic: docs/store-assets/feature-graphic-1024x500.png (1024x500)"
step "Screenshots:     the eight 1080x1920 files in docs/store-assets/play/"
step "Category Education. Contact email support@corlang.app."
warn "Name Croatian and Portuguese ONLY. fr, de, it and es are authored but hidden from"
warn "content/_index.json, so the installed app does not contain them."
pause "Listing saved?"

# -- 4 ---------------------------------------------------------------------
stage "App content (everything except App access)"
open_url "$CONSOLE"
step "Policy > App content. Work down the list:"
say ""
step "Ads:                 contains no ads."
step "Content rating:      educational, no objectionable content -> Everyone / PEGI 3."
step "Target audience:     13+, which avoids the children's-policy requirements."
step "Privacy policy URL:  https://corlang.app/privacy/"
step "Terms URL:           https://corlang.app/terms/"
step "Government / financial / health features: No."
note "docs/road-to-play.md still lists the old raw.githubusercontent PRIVACY.md URL."
note "The corlang.app pages are the live ones (PENDING.md, 2026-08-22)."
pause "App content saved, App access left alone?"

# -- 5 ---------------------------------------------------------------------
stage "Data safety"
say "This is the section that is easy to get wrong by answering from memory."
open_url "$CONSOLE"
step "Policy > App content > Data safety."
step "Follow docs/play-data-safety.md field by field. It was derived from the built"
step "manifest and the dependency list, not from recollection."
say ""
warn "Do NOT declare 'no data collected'. The optional AI tutor sends user-typed chat"
warn "text and the profile name off-device. Google counts transmitted-off-device as"
warn "collected, so a flat no-collection answer is a misdeclaration risk."
note "category 'Other in-app messages', purpose app functionality, not shared, optional."
note "everything else - lesson progress, SRS state, streak - is local-only; deletion = uninstall."
pause "Data safety saved?"

# -- 6 ---------------------------------------------------------------------
stage "App access - the attestation"
warn "On 2026-08-22 App access was saved as 'restricted', with the box ticked that says"
warn "the sign-in details give full access to all premium and paid content."
say ""
say "That claim is FALSE today. It carries no promo codes, because codes need products,"
say "and products need the merchant profile, which is deferred until registration."
say ""
note "Internal testing is not reviewed the way closed testing is, so nothing breaks today."
note "The form states the penalty for an untrue attestation: blocked updates, or removal."
say ""
say "To make it true: create the seven products, generate three codes (unlocks are"
say "cumulative, so the B1 product is the whole course), and replace the wording with"
say "the block in docs/PENDING.md under 'BLOCKING BEFORE CLOSED TESTING'."
note "codes needed: unlock_hr_b1, unlock_pt_b1, corlang_ai_premium"
say ""
if confirm "Are the products live, the three codes attached, and the wording replaced?"; then
  APP_ACCESS_TRUE=yes
  say "Recorded. Stage 9 will let the closed-testing clock start."
else
  APP_ACCESS_TRUE=no
  warn "Recorded as not-yet-true. Stage 9 will refuse to start closed testing."
fi
write_env APP_ACCESS_ATTESTATION_TRUE "$APP_ACCESS_TRUE"

# -- 7 ---------------------------------------------------------------------
stage "Upload to Internal testing"
say "Internal testing is live in minutes, has no review wait, and takes 100 testers."
say "Publishing to it is also what makes the Monetize in-app products page work at all."
open_url "$CONSOLE"
step "Test and release > Testing > Internal testing > Create release."
step "Upload this file:"
note "  $AAB"
step "Add a release note, review, then Roll out."
step "Then the Testers tab: create an email list with your own account, copy the opt-in URL."
ask INTERNAL_OPT_IN_URL "Paste the internal-testing opt-in URL:"
write_env INTERNAL_OPT_IN_URL "$INTERNAL_OPT_IN_URL"

# -- 8 ---------------------------------------------------------------------
stage "Device check - this is Track E"
say "No unit test reaches any of this, and the app has not been on hardware for"
say "several releases."
if [[ -n "${INTERNAL_OPT_IN_URL:-}" ]]; then open_url "$INTERNAL_OPT_IN_URL"; fi
step "On the phone: open the opt-in link, become a tester, install from Play."
step "Walk A0. Both courses are free for their first ten lessons."
step "Exercise every step type, the review queue, the streak across a midnight, the"
step "level quiz, and a reminder actually firing at the minute it is set."
say ""
warn "Any content defect found here becomes a NEW CHECK in tools/course/, per"
warn "docs/error-registry.md. Found once, checked forever - a defect fixed in one"
warn "lesson and not turned into a check comes back in the next course."
pause "Device pass done?"

# -- 9 ---------------------------------------------------------------------
stage "Closed testing - the 14-day clock"
if [[ "${APP_ACCESS_TRUE:-no}" != yes ]]; then
  warn "BLOCKED. Not starting closed testing while the App access attestation is untrue."
  say ""
  say "The chain, innermost first:"
  note "  a job        -> bijberoep (BE) or obrt (HR) registration"
  note "  registration -> merchant profile      [payments-profile country is PERMANENT]"
  note "  merchant     -> the seven products"
  note "  products     -> promo codes           [the build is already published, stage 7]"
  note "  codes        -> a true App access attestation"
  note "  attestation  -> closed testing: 12 testers, 14 continuous days"
  say ""
  warn "Consequence, accepted knowingly: the 14-day production gate now runs AFTER the job"
  warn "rather than in parallel with the job hunt. docs/PENDING.md (2026-08-28) argues the"
  warn "other way - re-read it before treating this block as settled."
  say ""
  say "Everything up to and including stage 8 is done, and needed no legal status."
  SKIPPED+=("closed testing: blocked on the App access attestation (stage 6)")
else
  open_url "$CONSOLE"
  step "Test and release > Testing > Closed testing > Create track."
  step "Add the SAME AAB, and an email list of at least 12 testers."
  step "Roll out, then check each tester has actually opted in. Opted-in is what counts."
  warn "12 testers, opted in, for 14 CONTINUOUS days. A gap restarts the clock."
  ask CLOSED_OPT_IN_URL "Paste the closed-testing opt-in URL:"
  ask CLOSED_START_DATE "Date the clock started (YYYY-MM-DD):"
  write_env CLOSED_OPT_IN_URL "$CLOSED_OPT_IN_URL"
  write_env CLOSED_START_DATE "$CLOSED_START_DATE"
  if ELIGIBLE=$(date -d "$CLOSED_START_DATE +14 days" +%Y-%m-%d 2>/dev/null); then
    say "Earliest production application: $ELIGIBLE"
    write_env PRODUCTION_ELIGIBLE_FROM "$ELIGIBLE"
  fi
fi
pause

# -- 10 --------------------------------------------------------------------
stage "Stop here - what must NOT be done yet"
warn "Do NOT submit the payments profile."
say "A payments profile's country can never be changed. Correcting it costs a new"
say "payments profile, a new developer account with its own fee, and a Play app"
say "transfer. Residence is genuinely open - Belgium or Croatia - so the form stays"
say "unsubmitted. It is the one irreversible click here, and testing does not need it."
say ""
warn "Do NOT create the seven products until registration is done."
note "product IDs are case-sensitive and can never be changed or reused once created."
say ""
warn "Do NOT set PLAY_SERVICE_ACCOUNT yet. Track B is for public production only."
say "verifySubscription FAILS OPEN: a bad key, a disabled API and a missing Play Console"
say "grant all end in 'return true'. A placeholder value silently switches verification"
say "on and 403s every real subscriber. When the time comes use 'secret bulk', not"
say "'secret put' - the hidden prompt reads one line and truncates a multi-line key -"
say "then verify with server/ai-proxy/check-play-access.py, because nothing else will."
pause "Understood?"

finish
